requires:
- name: "golang"
  category: "build"
  version: ">=0"
env:
- PATH=$PATH:/usr/local/go/bin
- GOPATH=/luetbuild/go
- GO111MODULE=off
- CGO_ENABLED=0
prelude:
{{ if .Values.distribution }}
  {{if eq .Values.distribution "opensuse" }}
- zypper in -y git
  {{else if eq .Values.distribution "fedora" }}
- dnf install -y git
  {{else if eq .Values.distribution "ubuntu" }}
- apt-get install -y git
   {{else if eq .Values.distribution "alpine" }}
- apk update && apk add git || true
   {{end}}
{{end}}
- |
   mkdir -p /luetbuild/go/src/github.com/u-root && cd /luetbuild/go/src/github.com/u-root && \
   git clone https://github.com/u-root/u-root && cd u-root && git checkout "{{.Values.git_sha}}" -b build
steps:
- |
   cd /luetbuild/go/src/github.com/u-root/u-root && go build -ldflags '-s -w' && mv u-root /usr/bin/u-root
includes:
- /usr/bin/u-root
excludes:
- ^/luetbuild
- ^/root