requires:
- category: "kernel"
  name: "vanilla"
  version: ">=0"
- category: "toolchain"
  name: "uroot"
  version: ">=0"

env:
- PATH=$PATH:/usr/local/go/bin
- GOPATH=/luetbuild/go
- GO111MODULE=off
- CGO_ENABLED=0
unpack: true
prelude:
{{ if .Values.distribution }}
  {{if eq .Values.distribution "opensuse" }}
- zypper in -y xz
  {{else if eq .Values.distribution "fedora" }}
- dnf install -y xz
  {{else if eq .Values.distribution "ubuntu" }}
- apt-get install -y xz
   {{else if eq .Values.distribution "alpine" }}
- apk update && apk add xz || true
   {{end}}
{{end}}
- mkdir /boot || true
- rm -rf $GOPATH/src/github.com/u-root/u-root/cmds/core/init
- cp -rf init $GOPATH/src/github.com/u-root/u-root/cmds/core

steps:

# grab deps library for udev probe init functionalities
- go get github.com/pilebones/go-udev
- go get github.com/mudler/go-kdetect
- mkdir modules
- find /lib/modules/**/kernel/fs  -exec cp -r {} --parents ./modules \;
- find /lib/modules/**/kernel/lib  -exec cp -r {} --parents ./modules \;
- find /lib/modules/**/kernel/crypto  -exec cp -r {} --parents ./modules \;
- find /lib/modules/**/kernel/crypto  -exec cp -r {} --parents ./modules \;
- find /lib/modules/**/kernel/drivers/usb  -exec cp -r {} --parents ./modules \;
- find /lib/modules/**/kernel/drivers/hid  -exec cp -r {} --parents ./modules \;
- find /lib/modules/**/kernel/drivers/input  -exec cp -r {} --parents ./modules \;
- find /lib/modules/**/kernel/drivers/block  -exec cp -r {} --parents ./modules \;
- find /lib/modules/**/kernel/drivers/ata -exec cp -r {} --parents ./modules \;
- find /lib/modules/**/kernel/drivers/md -exec cp -r {} --parents ./modules \;
- find /lib/modules/**/kernel/drivers/virtio  -exec cp -r --parents {} ./modules \;
- find /lib/modules/**/kernel/drivers/cdrom  -exec cp -r --parents {} ./modules \;
- find /lib/modules/**/kernel/drivers/scsi  -exec cp -r --parents {} ./modules \;

# Ethernet + address family: af_packet
- find /lib/modules/**/kernel/drivers/net/ethernet  -exec cp -r --parents {} ./modules \;
- find /lib/modules/**/kernel/net/packet  -exec cp -r --parents {} ./modules \;
- cp -rf /lib/modules/**/modules.* ./modules/lib/modules/**/

- |
   u-root \
   -files "/luetbuild/loader.sh:/loader" \
   -files "/luetbuild/modules/lib/modules:/lib/modules" \
   -files "$(which blkid)" \
   -files "$(which mount)" \
   -files "$(which modprobe)" \
   -files "$(which depmod)" \
   -files "$(which losetup)" \
   -files "$(which setsid)" \
   -files "$(which switch_root)" \
   -files "$(which mkdir)" \
   -files "$(which sh)" \
   -files "$(which bash)" \
   -format=cpio -build=bb -initcmd="/init" -defaultsh="" -o initramfs.cpio \
   github.com/u-root/u-root/cmds/core/ip \
   github.com/u-root/u-root/cmds/core/ls \
   github.com/u-root/u-root/cmds/core/dhclient \
   github.com/u-root/u-root/cmds/core/init \
   github.com/u-root/u-root/cmds/core/cat \
   github.com/u-root/u-root/cmds/core/echo \
   github.com/u-root/u-root/cmds/core/chroot \
   github.com/u-root/u-root/cmds/core/sleep

- |
   xz --check=crc32 -9 --lzma2=dict=1MiB \
      --stdout initramfs.cpio \
      | dd conv=sync bs=512 \
      of=/boot/initrd
includes:
- ^/boot$
- ^/boot/initrd
excludes:
- ^/luetbuild
- ^/root